name: First interaction
  uses: actions/first-interaction@v1.1.0
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    description: 'DONT FORGET TO STAR THIS REPO!!'
    pr-message: # optional
    description: 'DONT FORGET TO STAR THIS REPO!!'
