name: Summary

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
   starcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Please Star Light
        uses: QXIP/please-star-light@v3
        
      with:
        token: ${{ secrets.GH_TOKEN }}
        message: "Please star this repository to motivate developers! :star:"
        # label: "stargazed"
        # autoclose: true
